- name: "b1000分"
  price: "¥52"
  description: "不影响正常使用，只需要uid，量多有优惠"

- name: "xhs 100分"
  price: "¥40"
  description: "秒上不排队"

- name: "xhs 1000小眼睛-uv"
  price: "¥48"
  description: ""

- name: "xhs 1000小眼睛"
  price: "¥15"
  description: "无视风控，无视作品，绝不伤号"

- name: "sph 1000拨"
  price: "¥2"
  description: "打开视频号，找到视频，点击右上角...3个点，下拉点击复制视频ID或是复制链接进入下单"

- name: "sph真机1000拨"
  price: "¥20"
  description: "真机操作"

- name: "sph 100分"
  price: "¥20"
  description: "真机操作，也有adq加值套餐可以咨询"

- name: "sph拇指100"
  price: "¥15"
  description: ""
